services:
  nuxt:
    command: /usr/local/bin/npm run dev:debug
    volumes:
      - ./:/heimr-server
      - /heimr-server/node_modules
    env_file:
      - .env
      - .env.docker
    build:
      target: dev
    ports:
      - "9210:9210"
    environment:
      NODE_ENV: "development"

  mongodb-express:
    image: mongo-express
    container_name: heimr-mongodb-express
    env_file:
      - .env
      - .env.docker
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:27017/${MONGODB_DATABASE}?authSource=admin"
      ME_CONFIG_BASICAUTH_USERNAME: "dev"
      ME_CONFIG_BASICAUTH_PASSWORD: "dev"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "8012:8081"
    networks:
      - heimr_external_client_net
      - heimr_db_net